- name: Ansible Tower Git Repo
  hosts: all
  remote_user: ubuntu
  become: true
  tasks:
  - name: Clone Git Repo
    git:
      repo: 'https://adhig93:AWSdevops*123@github.com:adhig93/Ansible-Tower-with-Terraform.git'
      dest: /etc/ansible/git/
      version: main
      accept_hostkey: yes
  - name: Cloning Terraform Files  
    git:
      repo: 'git@github.com:adhig93/VPC-Simple.git'
      dest: /etc/ansible/VPC/
      version: master
      accept_hostkey: yes 
  - name: Pushing Terraform Files to Github
    shell: |
      rm -rf /etc/ansible/git/*
      mkdir /etc/ansible/git/VPC-Simple
      cp -r /etc/ansible/VPC/* /etc/ansible/git/VPC-Simple
      rm -rf /etc/ansible/VPC
      cd /etc/ansible/git
      git add -A && git commit -m "Added Files" && git push
